# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('rate_limit', 'Rate Limiting'), ('ip_check', 'IP Address Check'), ('device_fingerprint', 'Device Fingerprint'), ('behavioral', 'Behavioral Analysis'), ('account_score', 'Account Score Check')], max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('threshold', models.FloatField(default=0.0)),
                ('action', models.CharField(default='flag', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_detection_rules',
            },
        ),
        migrations.CreateModel(
            name='ManualReviewQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'manual_review_queue',
                'ordering': ['priority', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('deterministic', 'Deterministic Check'), ('tokenized', 'Tokenized Verification'), ('screenshot', 'Screenshot Analysis'), ('headless', 'Headless Browser'), ('manual', 'Manual Review'), ('ml', 'Machine Learning')], max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(default=dict)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('website', 'Website')], max_length=20)),
                ('engagement_type', models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('comment', 'Comment'), ('share', 'Share'), ('visit', 'Website Visit'), ('subscribe', 'Subscribe'), ('view', 'View')], max_length=20)),
                ('verification_methods', models.JSONField(default=list)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('retry_attempts', models.PositiveIntegerField(default=3)),
                ('min_confidence_score', models.FloatField(default=0.8)),
                ('auto_approve_threshold', models.FloatField(default=0.9)),
                ('auto_reject_threshold', models.FloatField(default=0.3)),
                ('platform_settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verification_rules',
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('current_method', models.CharField(blank=True, max_length=20)),
                ('method_results', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('ml_model_version', models.CharField(blank=True, max_length=50)),
                ('ml_features', models.JSONField(default=dict)),
                ('job_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_session', to='jobs.jobattempt')),
                ('verification_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.verificationrule')),
            ],
            options={
                'db_table': 'verification_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='verificationrule',
            index=models.Index(fields=['platform'], name='verificatio_platfor_81fe8d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrule',
            index=models.Index(fields=['engagement_type'], name='verificatio_engagem_5897aa_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrule',
            index=models.Index(fields=['is_active'], name='verificatio_is_acti_15a1cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationrule',
            unique_together={('platform', 'engagement_type')},
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='verification_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verification.verificationsession'),
        ),
        migrations.AddField(
            model_name='manualreviewqueue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualreviewqueue',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualreviewqueue',
            name='job_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_review', to='jobs.jobattempt'),
        ),
        migrations.AddIndex(
            model_name='frauddetection',
            index=models.Index(fields=['rule_type'], name='fraud_detec_rule_ty_331b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='frauddetection',
            index=models.Index(fields=['is_active'], name='fraud_detec_is_acti_661f42_idx'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='fraud_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.frauddetection'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='job_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobattempt'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['status'], name='verificatio_status_a75cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['started_at'], name='verificatio_started_d654e7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['timeout_at'], name='verificatio_timeout_c58ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verification_type'], name='verificatio_verific_6c4049_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['success'], name='verificatio_success_2e704b_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['request_timestamp'], name='verificatio_request_bcfec7_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['status'], name='manual_revi_status_8273ba_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['priority'], name='manual_revi_priorit_561eed_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['assigned_to'], name='manual_revi_assigne_fe429c_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['queued_at'], name='manual_revi_queued__ff8ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['severity'], name='fraud_alert_severit_7c3d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status'], name='fraud_alert_status_cf1609_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['user'], name='fraud_alert_user_id_a2a1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['triggered_at'], name='fraud_alert_trigger_d5b1ad_idx'),
        ),
    ]
