# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_suspend', 'Suspend User'), ('user_ban', 'Ban User'), ('user_verify', 'Verify User'), ('campaign_pause', 'Pause Campaign'), ('campaign_cancel', 'Cancel Campaign'), ('campaign_refund', 'Refund Campaign'), ('job_approve', 'Approve Job'), ('job_reject', 'Reject Job'), ('withdrawal_approve', 'Approve Withdrawal'), ('withdrawal_reject', 'Reject Withdrawal'), ('wallet_adjust', 'Adjust Wallet'), ('system_config', 'System Configuration'), ('bulk_action', 'Bulk Action')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('bulk_count', models.PositiveIntegerField(default=1)),
                ('bulk_targets', models.JSONField(blank=True, default=list)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('trigger', models.CharField(choices=[('user_registration', 'User Registration'), ('email_verification', 'Email Verification'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('campaign_funded', 'Campaign Funded'), ('campaign_completed', 'Campaign Completed'), ('job_accepted', 'Job Accepted'), ('job_verified', 'Job Verified'), ('job_failed', 'Job Failed'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_failed', 'Withdrawal Failed'), ('account_suspended', 'Account Suspended'), ('account_banned', 'Account Banned'), ('manual_review_assigned', 'Manual Review Assigned'), ('fraud_alert', 'Fraud Alert')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('verified_users', models.PositiveIntegerField(default=0)),
                ('total_campaigns', models.PositiveIntegerField(default=0)),
                ('active_campaigns', models.PositiveIntegerField(default=0)),
                ('completed_campaigns', models.PositiveIntegerField(default=0)),
                ('total_campaign_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('verified_jobs', models.PositiveIntegerField(default=0)),
                ('failed_jobs', models.PositiveIntegerField(default=0)),
                ('flagged_jobs', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pending_withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('verification_rate', models.FloatField(default=0.0)),
                ('dispute_rate', models.FloatField(default=0.0)),
                ('fraud_rate', models.FloatField(default=0.0)),
                ('avg_verification_time_minutes', models.FloatField(default=0.0)),
                ('api_requests', models.PositiveIntegerField(default=0)),
                ('api_errors', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('account', 'Account Issues'), ('payment', 'Payment Issues'), ('verification', 'Verification Issues'), ('technical', 'Technical Issues'), ('billing', 'Billing Issues'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feature_request', 'Feature Request')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('config_type', models.CharField(choices=[('platform', 'Platform Settings'), ('verification', 'Verification Settings'), ('payment', 'Payment Settings'), ('security', 'Security Settings'), ('notification', 'Notification Settings'), ('feature_flag', 'Feature Flag')], max_length=20)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_configurations',
            },
        ),
    ]
