# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['promoter'], name='campaigns_promote_5a6267_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['engagement_type'], name='campaigns_engagem_528a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['platform'], name='campaigns_platfor_9fc024_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_deleted'], name='campaigns_is_dele_de0e13_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='campaigns_created_9201e5_idx'),
        ),
    ]
