# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('comment', 'Comment'), ('share', 'Share'), ('visit', 'Website Visit'), ('subscribe', 'Subscribe'), ('view', 'View')], max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_url', models.URLField()),
                ('target_identifier', models.CharField(blank=True, max_length=255)),
                ('acceptance_criteria', models.JSONField(default=dict)),
                ('comment_templates', models.JSONField(blank=True, default=list)),
                ('required_account_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_score', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_data', models.JSONField()),
                ('screenshot_urls', models.JSONField(blank=True, default=list)),
                ('tracking_token', models.CharField(blank=True, max_length=255)),
                ('comment_text', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('verifier_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'job_attempts',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_entry', to='jobs.job')),
            ],
            options={
                'db_table': 'job_feed',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
