# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobattempt',
            name='earner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobattempt',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='job',
            name='earner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobfeed',
            index=models.Index(fields=['platform'], name='job_feed_platfor_4a8351_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfeed',
            index=models.Index(fields=['action_type'], name='job_feed_action__dd9a66_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfeed',
            index=models.Index(fields=['reward_amount'], name='job_feed_reward__5ddc97_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfeed',
            index=models.Index(fields=['priority_score'], name='job_feed_priorit_691238_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfeed',
            index=models.Index(fields=['created_at'], name='job_feed_created_5712eb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['job'], name='job_attempt_job_id_c04deb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['earner'], name='job_attempt_earner__c5e4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['verification_status'], name='job_attempt_verific_556d28_idx'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['submitted_at'], name='job_attempt_submitt_23cecf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['campaign'], name='jobs_campaig_27cd93_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['earner'], name='jobs_earner__d67f75_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['action_type'], name='jobs_action__4be6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority'], name='jobs_priorit_abca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['expires_at'], name='jobs_expires_503a37_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_deleted'], name='jobs_is_dele_1c5b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'),
        ),
    ]
