# Generated by Django 4.2.7 on 2025-09-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe_connect', 'Stripe Connect'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('payment_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider_id', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user'], name='withdrawals_user_id_4acc87_idx'), models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'), models.Index(fields=['payment_method'], name='withdrawals_payment_0c69a7_idx'), models.Index(fields=['requested_at'], name='withdrawals_request_d97b9f_idx'), models.Index(fields=['is_deleted'], name='withdrawals_is_dele_dab671_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('hold', 'Hold'), ('credit', 'Credit'), ('debit', 'Debit'), ('fee', 'Fee'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('commission', 'Commission')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_provider_id', models.CharField(blank=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['user'], name='wallet_tran_user_id_97baf4_idx'), models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'), models.Index(fields=['reference'], name='wallet_tran_referen_531c6d_idx'), models.Index(fields=['status'], name='wallet_tran_status_c987ce_idx'), models.Index(fields=['processed_at'], name='wallet_tran_process_5f66af_idx'), models.Index(fields=['is_deleted'], name='wallet_tran_is_dele_2b3eaa_idx')],
            },
        ),
    ]
